services:
  mysql:
    container_name: ficas-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ficas_db
      MYSQL_USER: ficas_user
      MYSQL_PASSWORD: ficas_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    container_name: ficas-backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    container_name: ficas-frontend
    build: ./frontend
    ports:
      - "5173:5173"
volumes:
  mysql_data:
    