services:
  mysql:
    container_name: ficas-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_EXTRA_USER}
      MYSQL_PASSWORD: ${DB_EXTRA_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./forensic_admin.sql:/docker-entrypoint-initdb.d/forensic_admin.sql:ro
  backend:
    container_name: ficas-backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    container_name: ficas-frontend
    build: ./frontend
    ports:
      - "5173:5173"
volumes:
  mysql_data:
    