services:
  backend:
    container_name: ficas-backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
  frontend:
    container_name: ficas-frontend
    build: ./frontend
    ports:
      - "5173:5173"
    
    